Chore: add statemint routers config
interlay/bridge pull request #17
Opened 2022-11-22 15:17 UTC by bvotteler

2022-11-22 15:48 UTC, sander2 requested changes

2022-11-22 16:50 UTC, bvotteler commented on src/bridge.spec.ts
> +    // printBidirectionalTxs("kintsugi", "statemine", "USDT");
> Why disable? Would be better to leave them enabled to make sure the changes didn't accidentally break anything

I had them disabled for the last few runs. They still worked.
Good shout. Let me reenable them

2022-11-22 17:07 UTC, bvotteler commented on src/adapters/statemint.ts
> +    to: "polkadot",
> Why do you want to support sending dot to polkadot from statemint? I have nothing against it, just curious

I wasn't thinking too deeply about this. I simply added the obvious connections.

2022-11-22 17:09 UTC, bvotteler commented on src/bridge.spec.ts
> +    printBidirectionalTxs("statemint", "interlay", "USDT");
> The `printBidirectionalTxs` is already for both directions, so no need to have both here

Ah, thanks for pointing that out. The name makes it kinda obvious... and yet I missed it :P

2022-11-23 09:56 UTC, sander2 approved these changes

2022-11-23 09:56 UTC, merged